version: 0.0
Resources:
- workloadProxy:
    Type: "AWS::Lambda::Function"
    Properties:
      Name: "scheduler-workloadProxy"
      Alias: "DEV"
      CurrentVersion: "3"
      TargetVersion: "3"

