version: 0.2

#run-as: Linux-user-name  # optional.  Otherwise runs as root

#env:
#  variables:
#    key: "value"
#    key: "value"
#  parameter-store:
#    key: "value"
#    key: "value"

phases:
  install:
#    run-as: Linux-user-name
    commands:
      - echo Entered the [install] phase...
      # install dependencies for scheduler
      # install pip installer
      - echo apt-get updating
      - sudo apt-get update -y

      - echo installing python3-pip
      - sudo apt-get install -y python3-pip

      - echo installing zip
      - sudo apt-get install -y zip
#    finally:
#      - command
#      - command
  pre_build:
#    run-as: Linux-user-name
    commands:
      - echo Entered the [pre_build] phase...
      - echo "Code source build directory is $CODEBUILD_SRC_DIR"
      - ls -lR $CODEBUILD_SRC_DIR

      - echo creating build directory buildDir
      - mkdir buildDir

      - echo Copying python files to build directory
      - mv serverless/lambda/*.py buildDir

      - echo Copying appspec.yml files to build directory
      - mv appspec.yaml buildDir

      # install retry module
      - echo installing retry module in buildDir
      - sudo pip3 install retry -t buildDir
#    finally:
#      - command
#      - command
  build:
#    run-as: Linux-user-name
    commands:
      - echo Entered the [build] phase...
      - cd buildDir
      - zip -r ../serverless/lambda/scheduler-workloadproxy.zip  .
#      - command
#    finally:
#      - command
#      - command
  post_build:
    commands:
      # Enter zip command to construct the zip file
      - echo Entered the [post_build] phase...
#    finally:
#      - command
#      - command
artifacts:
  files:
    - **/*
  discard-paths: yes
  base-directory: buildDir
#  secondary-artifacts:
#    artifactIdentifier:
#      files:
#        - location
#        - location
#      discard-paths: yes
#      base-directory: location
#    artifactIdentifier:
#      files:
#        - location
#        - location
#      discard-paths: yes
#      base-directory: location
#cache:
#  paths:
#    - path
#    - path
