

REQUEST_PARAM_WORKLOAD = 'workloadName'
REQUEST_PARAM_DRYRUN = 'dryRun'
REQUEST_PARAM_ACTION = 'action'

REQUEST_EVENT_WORKLOAD_KEY = 'workload'
REQUEST_EVENT_PATHPARAMETER_KEY = 'pathParameters'
REQUEST_EVENT_QUERY_STR_PARAMETERS_KEY = 'queryStringParameters'

# What is the request trying to do ?
REQUEST_DIRECTIVE = 'directive'
REQUEST_DIRECTIVE_LIST_ALL_WORKLOADS_SPECS = 'listAllWorkloads'
REQUEST_DIRECTIVE_LIST_WORKLOAD_SPEC = 'listWorkload'
REQUEST_DIRECTIVE_ACTION_STOP = 'stopAction'
REQUEST_DIRECTIVE_ACTION_START = 'startAction'
REQUEST_DIRECTIVE_UNKNOWN = 'directiveUnknown'

RESULT_CODE_BAD_REQUEST = 400
RESULT_CODE_OK_REQUEST = 200
RESULT_BODY = 'body'
RESULT_BASE_64 = 'isBase64Encoded'
RESULT_HEADERS = 'headers'
RESULT_STATUS_CODE = 'statusCode'
RESULT_WORKLOAD_SPEC = 'workloadSpec'
RESULT_LIST_ALL_WORKLOADS_REQUEST = 'listAllWorkloads'

ACTION_START='Start'
ACTION_STOP='Stop'
ACTION_SCALE='Scale'
NO_METHOD_FOUND='NoMethodFound'
